/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from "./common";
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from "ethers";

export declare namespace ICommunityPortal {
  export type CommunityStruct = {
    communityURI: string;
    passport: AddressLike;
    closed: boolean;
  };

  export type CommunityStructOutput = [
    communityURI: string,
    passport: string,
    closed: boolean,
  ] & { communityURI: string; passport: string; closed: boolean };
}

export interface CommunityPortalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addExp"
      | "communitySupply"
      | "createCommunity"
      | "getCommunity"
      | "getCommunityList"
      | "initialize"
      | "owner"
      | "passportCreater"
      | "proxiableUUID"
      | "questBoard"
      | "renounceOwnership"
      | "setClosed"
      | "setCommunityURI"
      | "setPassport"
      | "setPassportCreater"
      | "setQuestBoard"
      | "transferOwnership"
      | "upgradeTo"
      | "upgradeToAndCall",
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "CreatedCommunity"
      | "Initialized"
      | "OwnershipTransferred"
      | "SetCommunityURI"
      | "SetPassportCreater"
      | "Upgraded",
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExp",
    values: [BigNumberish, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "communitySupply",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "createCommunity",
    values: [string, string, string, string, AddressLike[], string],
  ): string;
  encodeFunctionData(
    functionFragment: "getCommunity",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "getCommunityList",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "passportCreater",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "questBoard",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "setClosed",
    values: [BigNumberish, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "setCommunityURI",
    values: [BigNumberish, string],
  ): string;
  encodeFunctionData(
    functionFragment: "setPassport",
    values: [BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setPassportCreater",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setQuestBoard",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike],
  ): string;

  decodeFunctionResult(functionFragment: "addExp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "communitySupply",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCommunity",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommunity",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommunityList",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "passportCreater",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "questBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "setClosed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCommunityURI",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPassport",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPassportCreater",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuestBoard",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike,
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatedCommunityEvent {
  export type InputTuple = [
    publisher: AddressLike,
    communityId: BigNumberish,
    communityPassport: AddressLike,
    communityURI: string,
  ];
  export type OutputTuple = [
    publisher: string,
    communityId: bigint,
    communityPassport: string,
    communityURI: string,
  ];
  export interface OutputObject {
    publisher: string;
    communityId: bigint;
    communityPassport: string;
    communityURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetCommunityURIEvent {
  export type InputTuple = [
    communityId: BigNumberish,
    oldState: string,
    newState: string,
  ];
  export type OutputTuple = [
    communityId: bigint,
    oldState: string,
    newState: string,
  ];
  export interface OutputObject {
    communityId: bigint;
    oldState: string;
    newState: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetPassportCreaterEvent {
  export type InputTuple = [
    publisher: AddressLike,
    oldState: AddressLike,
    newState: AddressLike,
  ];
  export type OutputTuple = [
    publisher: string,
    oldState: string,
    newState: string,
  ];
  export interface OutputObject {
    publisher: string;
    oldState: string;
    newState: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommunityPortal extends BaseContract {
  connect(runner?: ContractRunner | null): BaseContract;
  attach(addressOrName: AddressLike): this;
  deployed(): Promise<this>;

  interface: CommunityPortalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  addExp: TypedContractMethod<
    [communityId_: BigNumberish, user_: AddressLike, exp_: BigNumberish],
    [void],
    "nonpayable"
  >;

  communitySupply: TypedContractMethod<[], [bigint], "view">;

  createCommunity: TypedContractMethod<
    [
      name_: string,
      baseURI_: string,
      firstURI_: string,
      contractURI_: string,
      adminList_: AddressLike[],
      communityURI_: string,
    ],
    [void],
    "nonpayable"
  >;

  getCommunity: TypedContractMethod<
    [communityId_: BigNumberish],
    [ICommunityPortal.CommunityStructOutput],
    "view"
  >;

  getCommunityList: TypedContractMethod<
    [page_: BigNumberish, pageSize_: BigNumberish],
    [ICommunityPortal.CommunityStructOutput[]],
    "view"
  >;

  initialize: TypedContractMethod<
    [passportCreater_: AddressLike, questBoard_: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  passportCreater: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  questBoard: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setClosed: TypedContractMethod<
    [communityId_: BigNumberish, newState_: boolean],
    [void],
    "nonpayable"
  >;

  setCommunityURI: TypedContractMethod<
    [communityId_: BigNumberish, newState_: string],
    [void],
    "nonpayable"
  >;

  setPassport: TypedContractMethod<
    [communityId_: BigNumberish, newState_: AddressLike],
    [void],
    "nonpayable"
  >;

  setPassportCreater: TypedContractMethod<
    [newState_: AddressLike],
    [void],
    "nonpayable"
  >;

  setQuestBoard: TypedContractMethod<
    [newState_: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "addExp",
  ): TypedContractMethod<
    [communityId_: BigNumberish, user_: AddressLike, exp_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "communitySupply",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCommunity",
  ): TypedContractMethod<
    [
      name_: string,
      baseURI_: string,
      firstURI_: string,
      contractURI_: string,
      adminList_: AddressLike[],
      communityURI_: string,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCommunity",
  ): TypedContractMethod<
    [communityId_: BigNumberish],
    [ICommunityPortal.CommunityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommunityList",
  ): TypedContractMethod<
    [page_: BigNumberish, pageSize_: BigNumberish],
    [ICommunityPortal.CommunityStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize",
  ): TypedContractMethod<
    [passportCreater_: AddressLike, questBoard_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "passportCreater",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "questBoard",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setClosed",
  ): TypedContractMethod<
    [communityId_: BigNumberish, newState_: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCommunityURI",
  ): TypedContractMethod<
    [communityId_: BigNumberish, newState_: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPassport",
  ): TypedContractMethod<
    [communityId_: BigNumberish, newState_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPassportCreater",
  ): TypedContractMethod<[newState_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuestBoard",
  ): TypedContractMethod<[newState_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership",
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo",
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall",
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminChanged",
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded",
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "CreatedCommunity",
  ): TypedContractEvent<
    CreatedCommunityEvent.InputTuple,
    CreatedCommunityEvent.OutputTuple,
    CreatedCommunityEvent.OutputObject
  >;
  getEvent(
    key: "Initialized",
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred",
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SetCommunityURI",
  ): TypedContractEvent<
    SetCommunityURIEvent.InputTuple,
    SetCommunityURIEvent.OutputTuple,
    SetCommunityURIEvent.OutputObject
  >;
  getEvent(
    key: "SetPassportCreater",
  ): TypedContractEvent<
    SetPassportCreaterEvent.InputTuple,
    SetPassportCreaterEvent.OutputTuple,
    SetPassportCreaterEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded",
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "CreatedCommunity(address,uint32,address,string)": TypedContractEvent<
      CreatedCommunityEvent.InputTuple,
      CreatedCommunityEvent.OutputTuple,
      CreatedCommunityEvent.OutputObject
    >;
    CreatedCommunity: TypedContractEvent<
      CreatedCommunityEvent.InputTuple,
      CreatedCommunityEvent.OutputTuple,
      CreatedCommunityEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SetCommunityURI(uint32,string,string)": TypedContractEvent<
      SetCommunityURIEvent.InputTuple,
      SetCommunityURIEvent.OutputTuple,
      SetCommunityURIEvent.OutputObject
    >;
    SetCommunityURI: TypedContractEvent<
      SetCommunityURIEvent.InputTuple,
      SetCommunityURIEvent.OutputTuple,
      SetCommunityURIEvent.OutputObject
    >;

    "SetPassportCreater(address,address,address)": TypedContractEvent<
      SetPassportCreaterEvent.InputTuple,
      SetPassportCreaterEvent.OutputTuple,
      SetPassportCreaterEvent.OutputObject
    >;
    SetPassportCreater: TypedContractEvent<
      SetPassportCreaterEvent.InputTuple,
      SetPassportCreaterEvent.OutputTuple,
      SetPassportCreaterEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
