/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { IQuestChecker, IQuestCheckerInterface } from "../IQuestChecker";
import { Contract, ContractRunner, Interface } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
    ],
    name: "checkCompleted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IQuestChecker__factory {
  static readonly abi = _abi;
  static createInterface(): IQuestCheckerInterface {
    return new Interface(_abi) as IQuestCheckerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IQuestChecker {
    return new Contract(address, _abi, runner) as unknown as IQuestChecker;
  }
}
